# 1.9+ behaviors
bind c new-window -c '#{pane_current_path}'

# set shell
set-option -g default-shell /usr/local/bin/fish

set -g prefix C-a
bind-key a send-prefix
 
# disable auto renaming
set-window-option -g automatic-rename off
set-option -g allow-rename off

# enable utf8
setw -g utf8 on

# indexes 
set -g base-index 1
set -g pane-base-index 1

# history
set -g history-limit 4096

# sensible bindings
unbind %

bind | split-window -h
bind - split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim like copy/paste
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

# copy mode
setw -g mode-keys vi

# colors
set -g default-terminal "screen-256color"

# misc bindings
bind R source-file ~/.tmux.conf

# aggressive resizing in the case of multiple windows
setw -g aggressive-resize on

# toggle status
bind-key b set-option status

# Status update interval
set -g status-interval 1

# Right side of status bar
rs_mail="✉ #(mail-check.sh)"
#rs_weather="#[fg=#6a6a6a]#[bg=#6a6a6a fg=#ffffff] #(cat /tmp/weather.txt)"
rs_date="#[fg=#282a2e]#[bg=#282a2e fg=#1278a8] %a %H:%M:%S %b %d %Y"
rs_battery="#[fg=#000000]#[bg=#000000 fg=#1278a8] #{battery_percentage} "
set -g status-right-length 200
set -g status-right "$rs_mail #[bold]$rs_date $rs_battery"

# Left side of status bar
set -g status-left ""

# Window status
num_circle=" #(tmux-id.sh #I) "
set -g window-status-format $num_circle
set -g window-status-current-format $num_circle

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify left

# set status bar
set -g status-bg "#000000"
set -g status-fg "#c5c8c6"

set -g status-right-bg "#000000"
set -g status-right-fg "#55C0D2"

# highlight active window
setw -g window-status-current-bg "#282a2e"
setw -g window-status-current-fg "#1278A8"

# highlight activity in status bar
setw -g window-status-activity-fg "#8abeb7"
setw -g window-status-activity-bg "#1d1f21"

# pane border and colors
set -g pane-active-border-bg default
set -g pane-active-border-fg "#373b41"
set -g pane-border-bg default
set -g pane-border-fg "#373b41"

set -g clock-mode-colour "#81a2be"
set -g clock-mode-style 24

set -g message-bg "#8abeb7"
set -g message-fg "#000000"

set -g message-command-bg "#8abeb7"
set -g message-command-fg "#000000"

set -g mode-bg "#8abeb7"
set -g mode-fg "#000000"

# powerline
set-option -g status-position top
run-shell ~/.tmux-plugins/tmux-battery/battery.tmux
