hack: &hack Hack Nerd Font:pixelsize=12
jet: &jet Jet Brains Mono:pixelsize=14:weight=bold
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14

bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}

bar:
  monitor: DP-3
  height: 30
  location: bottom
  font: JuliaMono:pixelsize=10
  spacing: 2
  margin: 0
  layer: bottom
  foreground: DCD7BAFF
  background: 16161DFF

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13 
              default: {string: {text: , font: *hack}}
              conditions:
                id == 1: {string: {text: ﳐ, font: *hack}}  
                id == 2: {string: {text: 2, font: *hack}}  
                id == 3: {string: {text: 3, font: *hack}}  
                id == 4: {string: {text: 4, font: *hack}}  
                id == 5: {string: {text: 5, font: *hack}}  
                id == 6: {string: {text: 6, font: *hack}}  
                id == 7: {string: {text: 7, font: *hack}}  
                id == 8: {string: {text: 8, font: *hack}}  
                id == 9: {string: {text: 9, font: *hack}}  
        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: ea6962ff}}

  right:
    - clock:
        date-format: "%Y-%m-%d"
        time-format: "%I:%M %p"
        content:
          - string: {text: "{date} {time}", font: *jet, right-margin: 5, left-margin: 5}
